---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: chaos-testing
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monkey
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monkey
subjects:
  - kind: ServiceAccount
    name: default
    namespace: chaos-testing
  - kind: Group
    name: system:nodes
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monkey
  #namespace: chaos-testing 
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
      - services
    verbs:
      - get
      - list
      - watch
      - update
      - create
      - patch
      - delete


