apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: chaos-test-et-call-fqdn-{{ .Values.basename }}
spec:
  endpointSelector:
    matchLabels:
      name: {{ .Values.name }}
  egress:
  - toEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: kube-system
        k8s-app: kube-dns
    toPorts:
    - ports:
      - port: '53'
        protocol: UDP
      rules:
        dns:
          - matchPattern: "*.*"
          - matchPattern: "*.*.*"
  - toFQDNs:
      - matchName: {{ .Values.fqdn }}
