apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "chaos-slack-hook-allow"
spec:
  endpointSelector:
    matchLabels:
      name: {{ .Values.name }}
  egress:
  - toEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: kube-system
        k8s-app: kube-dns
    toPorts:
    - ports:
      - port: '53'
        protocol: UDP
  - toFQDNs:
    - matchName: "hooks.slack.com"
