apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-mario
spec:
  ports:
  - port: 80
  selector:
    statefulset.kubernetes.io/pod-name: {{ .Values.name }}-0
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-wario
spec:
  ports:
  - port: 80
  selector:
    statefulset.kubernetes.io/pod-name: {{ .Values.name }}-1
